openapi: 3.0.3
info:
  title: Swagger RS AWS Course Shop Backend
  version: 1.0.0
servers:
  - url: https://qehdxl0g4b.execute-api.eu-central-1.amazonaws.com
tags:
  - name: Products
paths:
  /products:
    get:
      tags:
        - Products
      summary: Get list of all products
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /products/{productId}:
    get:
      tags:
        - Products
      summary: Get product by id
      parameters:
        - name: productId
          in: path
          description: ID of the product to return
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number
      required:
        - id
        - title
        - price
        - count
